name: Build

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install coreutils build-essential libssl-dev zlib1g-dev # libcrypto-dev

      - name: Build
        run: |
          ./build-native.sh

      - name: Store Build
        uses: actions/upload-artifact@v4
        with:
          name: soeclient_ubuntu-22-04_amd64
          path: build/*.tar.xz
          compression-level: 0
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install MSYS ${{matrix.sys}} + gcc
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          # update: true
          pacboy: openssl:p pkg-config:p gcc:p binutils:p advancecomp:p
          install: mingw-w64-x86_64-7zip

      - name: Build Static
        run: |
          ./build-native.sh static

      - name: Store Build
        uses: actions/upload-artifact@v4
        with:
          name: soeclient_win64
          path: build/*.zip
          compression-level: 0
          if-no-files-found: error
